<h1> Getting started with TensorFlow </h1>

In this notebook, you play around with the TensorFlow Python API.

In [1]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

/usr/local/envs/py2env/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


1.8.0


<h2> Adding two tensors </h2>

First, let's try doing this using numpy, the Python numeric package. numpy code is immediately evaluated.

In [2]:
a = np.array([5, 3, 8])
b = np.array([3, -1, 2])
c = np.add(a, b)
print(c)

[ 8  2 10]


The equivalent code in TensorFlow consists of two steps:
<p>
<h3> Step 1: Build the graph </h3>

In [3]:
a = tf.constant([5, 3, 8])
b = tf.constant([3, -1, 2])
c = tf.add(a, b)
print(c)

Tensor("Add:0", shape=(3,), dtype=int32)


c is an Op ("Add") that returns a tensor of shape (3,) and holds int32. The shape is inferred from the computation graph.

Try the following in the cell above:
<ol>
<li> Change the 5 to 5.0, and similarly the other five numbers. What happens when you run this cell? </li>
<li> Add an extra number to a, but leave b at the original (3,) shape. What happens when you run this cell? </li>
<li> Change the code back to a version that works </li>
</ol>

<p/>
<h3> Step 2: Run the graph

In [4]:
with tf.Session() as sess:
  result = sess.run(c)
  print(result)

[ 8  2 10]


<h2> Using a feed_dict </h2>

Same graph, but without hardcoding inputs at build stage

In [5]:
a = tf.placeholder(dtype=tf.int32, shape=(None,))  # batchsize x scalar
b = tf.placeholder(dtype=tf.int32, shape=(None,))
c = tf.add(a, b)
with tf.Session() as sess:
    result = sess.run(c, feed_dict={
      a: [3, 4, 5],
      b: [-1, 2, 3]
    })
    print(result)

[2 6 8]


<h2> Heron's Formula in TensorFlow </h2>

The area of triangle whose three side lengths are $(a, b, c)$ is $\sqrt{s(s-a)(s-b)(s-c)}$ where $s=\frac{a+b+c}{2}$ 

Look up the available operations at: https://www.tensorflow.org/api_docs/python/tf. 

You'll need the `tf.sqrt()` operation. Remember `tf.add()`, `tf.subtract()` and `tf.multiply()` are overloaded with the +,- and * operators respectively.

You should get: 6.278497

In [8]:
def compute_area(sides):
    #TODO: Write TensorFlow code to compute area of a triangle
    #  given its side lengths
    s = tf.reduce_sum(sides) / 2
    print("s shape", s.get_shape())
    print("shape", tf.reduce_prod(s - sides).get_shape())
    area = tf.sqrt(s * tf.reduce_prod(s - sides))
    return area

with tf.Session() as sess:
    area = compute_area(tf.constant([5.0, 3.0, 7.1]))
    result = sess.run(area)
    print(result)

('s shape', TensorShape([]))
('shape', TensorShape([]))
6.278497


Extend your code to be able to compute the area for several triangles at once.

You should get: [6.278497 4.709139]

In [14]:
def compute_area(sides):
    #TODO: Write TensorFlow code to compute area of a 
    #  SET of triangles given by their side lengths
    total_triangles = sides.get_shape()[0]
    s = tf.reshape(tf.reduce_sum(sides, axis=1) / 2, shape=(total_triangles, 1))
    print(s.get_shape())
    print(tf.reduce_prod(s - sides, axis=1).get_shape())
    list_of_areas = tf.sqrt(tf.reshape(s, [-1]) * tf.reduce_prod(s - sides, axis=1))
    return list_of_areas

with tf.Session() as sess:
    # pass in two triangles
    area = compute_area(tf.constant([
      [5.0, 3.0, 7.1],
      [2.3, 4.1, 4.8]
    ]))
    result = sess.run(area)
    print(result)

(2, 1)
(2,)
[6.278497 4.709139]


<h2> Placeholder and feed_dict </h2>

More common is to define the input to a program as a placeholder and then to feed in the inputs. The difference between the code below and the code above is whether the "area" graph is coded up with the input values or whether the "area" graph is coded up with a placeholder through which inputs will be passed in at run-time.

Now if we use placeholder then above compute_area function will not work, because we are using get_shape() function.

Here, to create graph we need exact dimentions of batch, which we can't get. This will give an error when we call compute_area function and pass placeholder object.

https://github.com/tensorflow/tensorflow/issues/7253

In [15]:
with tf.Session() as sess:
    #TODO: Rather than feeding the side values as a constant, 
    #  use a placeholder and fill it using feed_dict instead.
    sides = tf.placeholder(dtype=tf.float32, shape=(None, 3))
    area = compute_area(sides)
    result = sess.run(area, feed_dict = {sides: [
      [5.0, 3.0, 7.1],
      [2.3, 4.1, 4.8]
    ]})
    print(result)

TypeError: Failed to convert object of type <type 'tuple'> to Tensor. Contents: (Dimension(None), 1). Consider casting elements to a supported type.

As we can see above this is giving error on calling compute_area() function.

To reshape value for s, it is setting its shape to (None,1).

We want its shape to be (shape_of_batch, 1)

__So what is the work around??__

We can use __tf.shape()__ which gives shape of a batch (placeholder).

__So, always use tf.shape(), when we want to reshape placeholder object by its shape.__

In [18]:
def compute_area(sides):
    #TODO: Write TensorFlow code to compute area of a 
    #  SET of triangles given by their side lengths
    total_triangles = tf.shape(sides)[0]
    s = tf.reshape(tf.reduce_sum(sides, axis=1) / 2, shape=(total_triangles, 1))
    print(s.get_shape())
    print(tf.shape(s))
    print(tf.reduce_prod(s - sides, axis=1).get_shape())
    print(tf.shape(tf.reduce_prod(s - sides, axis=1)))
    list_of_areas = tf.sqrt(tf.reshape(s, [-1]) * tf.reduce_prod(s - sides, axis=1))
    return list_of_areas
  
  
with tf.Session() as sess:
    #TODO: Rather than feeding the side values as a constant, 
    #  use a placeholder and fill it using feed_dict instead.
    sides = tf.placeholder(dtype=tf.float32, shape=(None, 3))
    area = compute_area(sides)
    result = sess.run(area, feed_dict = {sides: [
      [5.0, 3.0, 7.1],
      [2.3, 4.1, 4.8]
    ]})
    print(result)

(?, 1)
Tensor("Shape_1:0", shape=(2,), dtype=int32)
(?,)
Tensor("Shape_2:0", shape=(1,), dtype=int32)
[6.278497 4.709139]


## tf.eager

tf.eager allows you to avoid the build-then-run stages. However, most production code will follow the lazy evaluation paradigm because the lazy evaluation paradigm is what allows for multi-device support and distribution. 
<p>
One thing you could do is to develop using tf.eager and then comment out the eager execution and add in the session management code.

<b> You will need to click on Reset Session to try this out </b>

In [1]:
import tensorflow as tf
from tensorflow.contrib.eager.python import tfe
tf.enable_eager_execution()

#TODO: Using your non-placeholder solution, 
#  try it now using tf.eager by removing the session

def compute_area(sides):
    a = sides[:, 0]
    b = sides[:, 1]
    c = sides[:, 2]
    
    s = (a + b + c) / 2
    area = tf.sqrt(s * (s - a) * (s - b) * (s - c))
    
area = compute_area(tf.constant([
      [5.0, 3.0, 7.1],
      [2.3, 4.1, 4.8]
    ]))

print(area)


/usr/local/envs/py2env/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


None


## Challenge Exercise

Use TensorFlow to find the roots of a fourth-degree polynomial using [Halley's Method](https://en.wikipedia.org/wiki/Halley%27s_method).  The five coefficients (i.e. $a_0$ to $a_4$) of 
<p>
$f(x) = a_0 + a_1 x + a_2 x^2 + a_3 x^3 + a_4 x^4$
<p>
will be fed into the program, as will the initial guess $x_0$. Your program will start from that initial guess and then iterate one step using the formula:
<img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/142614c0378a1d61cb623c1352bf85b6b7bc4397" />
<p>
If you got the above easily, try iterating indefinitely until the change between $x_n$ and $x_{n+1}$ is less than some specified tolerance. Hint: Use [tf.where_loop](https://www.tensorflow.org/api_docs/python/tf/while_loop)

Copyright 2017 Google Inc. Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License